name: Integracion continua (CI)

on: 
    push: 
        branches: [ main, develop ]
    pull_request:
        branches: [ main ]

jobs: 
    build_and_test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout del codigo
          uses: actions/checkout@v4
        
        - name: configurar entorno (nodejs)
          uses: actions/setup-node@v4
          with:
             node-version: '20'
        - name: instalar dependencias
          run: npm install

        - name: correr tests
          run: npm run test
          